(function () {
  'use strict';
  const $ = id => document.getElementById(id);
  const base = window.QLStorefront?.apiBase || 'https://labapi.genziitian.in/public/api';
  let courses = [], papers = [], deletionRequests = [], current = null, questions = [], questionId = null, dirty = false, questionDirty = false, page = 1, lastPage = 1, toastTimer;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(value || 0)/100);
  const form = $('paper-form'), qform = $('question-form');
  const value = (f,key) => f.elements.namedItem(key).value;
  function token() { try { return localStorage.getItem('lab_token') || ''; } catch { return ''; } }
  function toast(text) { $('toast').textContent = text; $('toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').classList.remove('show'),5000); }
  async function api(path,method='GET',body) {
    const response = await fetch(base+path,{method,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:'Bearer '+token()},body:body === undefined ? undefined : JSON.stringify(body)});
    const data = await response.json().catch(() => ({}));
    if (response.status === 401) { try { localStorage.removeItem('lab_token'); localStorage.removeItem('lab_user'); } catch {} throw new Error('Your session expired. Sign in again, then reopen Manage sales.'); }
    if (!response.ok) { const errors = data.errors ? Object.values(data.errors).flat().join('\n') : ''; throw new Error(errors || data.message || data.error || 'Unable to complete this request. Please retry.'); }
    return data;
  }
  async function busy(button, action, status) { if (button.disabled) return; const original = button.textContent; button.disabled = true; button.textContent = 'Please wait…'; if (status) status.textContent = ''; try { await action(); } catch(error) { if(status) status.textContent = error.message; else toast(error.message); } finally {button.disabled=false;button.textContent=original;} }
  function state() { $('editor-state').textContent = current ? `${current.is_active ? 'Published' : 'Offline draft'} · ${questions.length} questions · ${money(current.price_paise)}${current.access_days ? ' · '+current.access_days+' days access' : ' · No expiry'}${dirty ? ' · Unsaved changes' : ''}` : 'New draft — save details before adding questions.'; $('add-question').disabled=!current || Boolean(current.is_active); $('question-lock').hidden=!current?.is_active; $('question-import').hidden=!current || Boolean(current.is_active); if (current?.is_active) qform.hidden=true; $('publish-paper').disabled=!current || dirty || questionDirty || !questions.length || Boolean(current.is_active); $('deactivate-paper').disabled=!current?.is_active; }
  function renderPapers() { const term=$('paper-search').value.trim().toLowerCase(); const rows=papers.filter(p => [p.title,p.course_name].join(' ').toLowerCase().includes(term)); $('paper-list').innerHTML=rows.length ? rows.map(p=>`<article class="card"><span class="badge ${p.is_active?'':'offline'}">${p.is_active?'Published':'Offline'}${p.approval_status!=='approved'?' · Review needed':''}</span>${p.course_active===false?'<span class="badge offline">Course inactive</span>':''}<h3>${esc(p.title)}</h3><p>${esc(p.course_name || p.course?.name)} · ${esc(p.section)}</p><p>${esc(p.questions_count || 0)} questions · ${esc(money(p.price_paise))}</p><button data-edit="${esc(p.id)}">Manage paper</button></article>`).join('') : '<div class="notice empty">No papers found. Create a paper to get started.</div>'; }
  async function refreshPapers() { papers=await api('/manager/papers'); renderPapers(); }
  function renderCourses() { $('course-list').innerHTML=courses.length ? courses.map(c=>`<article class="panel"><h3>${esc(c.name)}</h3><span class="badge">${esc(c.level)}</span><p class="hint">${esc(c.description || '')}</p><p>${c.is_active?'Active':'Inactive'}</p><button data-course-toggle="${esc(c.id)}">${c.is_active?'Deactivate course':'Activate course'}</button></article>`).join('') : '<div class="notice">Create your first course to organize its papers.</div>'; $('paper-course').innerHTML='<option value="">Choose a course</option>'+courses.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}${c.is_active?'':' (inactive)'}</option>`).join(''); }
  function renderDeletionRequests() {
    const target = $('deletion-request-list');
    const filter = $('deletion-request-filter').value;
    const rows = filter === 'all' ? deletionRequests : deletionRequests.filter(row => row.status === filter);
    $('deletion-request-count').textContent = `· ${deletionRequests.length} total`;
    target.innerHTML = rows.length ? rows.map(row => `<article class="panel">
      <div class="toolbar tight"><div><h3>${esc(row.name)} <span class="hint">· Request #${esc(row.id)}</span></h3><p class="hint">${esc(row.email)} · User ID ${esc(row.user_id ?? 'account removed')} · ${esc(row.role)}</p></div>
      <label>Status<select data-deletion-status="${esc(row.id)}"><option value="pending" ${row.status==='pending'?'selected':''}>Pending</option><option value="reviewing" ${row.status==='reviewing'?'selected':''}>Reviewing</option><option value="completed" ${row.status==='completed'?'selected':''}>Completed</option></select></label></div>
      <p><strong>Reason:</strong> ${esc(row.reason)}</p><p><strong>Additional details:</strong> ${esc(row.details || 'None provided')}</p>
      <p class="hint">Account created ${esc(row.account_created_at ? new Date(row.account_created_at).toLocaleString() : 'date unavailable')} · Requested ${esc(new Date(row.created_at).toLocaleString())}</p>
    </article>`).join('') : `<div class="notice empty">${deletionRequests.length ? 'No requests match this status.' : 'No account deletion requests have been submitted.'}</div>`;
  }
  async function loadDeletionRequests() { $('deletion-request-list').innerHTML='<div class="notice">Loading requests…</div>'; try { deletionRequests=await api('/manager/account-deletion-requests').then(data=>data.requests || []);renderDeletionRequests(); } catch(error) { $('deletion-request-list').innerHTML=`<div class="notice">${esc(error.message)}</div>`; } }
  async function loadWeeks(selected) { const weekly=['practice','practice_graded'].includes(value(form,'section')); $('week-field').hidden=!weekly; $('paper-week').required=weekly; if(!weekly) return; $('paper-week').innerHTML='<option value="">Loading weeks…</option>'; if(!value(form,'course_id')) return; try { const rows=await api('/manager/courses/'+encodeURIComponent(value(form,'course_id'))+'/weeks'); $('paper-week').innerHTML='<option value="">Choose a week</option>'+rows.map(w=>`<option value="${esc(w.id)}">Week ${esc(w.week_number)}${w.title?' — '+esc(w.title):''}</option>`).join(''); if(selected) $('paper-week').value=selected; } catch(error){toast(error.message);} }
  function editTab(tab) { ['details','questions','preview'].forEach(name=>$(name+'-step').hidden=name!==tab); document.querySelectorAll('[data-edit-tab]').forEach(b=>b.classList.toggle('active',b.dataset.editTab===tab)); if(tab==='preview') renderPreview(); }
  async function openEditor(id) { if(dirty || questionDirty) { if(!confirm('Discard unsaved changes and open this paper?')) return; } form.reset(); qform.hidden=true; questionId=null; questions=[];dirty=false;questionDirty=false;current=null; form.querySelector('.form-status').textContent=''; $('publish-status').textContent=''; if(id) { current=await api('/manager/papers/'+id); questions=await api('/manager/papers/'+id+'/questions'); for(const key of ['title','description','course_id','section','year','time_limit_minutes','access_days']) form.elements.namedItem(key).value=current[key] ?? ''; form.elements.price.value=Number(current.price_paise || 0)/100; } $('editor-title').textContent=current?'Edit paper':'Create a paper'; await loadWeeks(current?.week_id); renderQuestions(); editTab('details'); state(); if(!$('editor').open) $('editor').showModal(); }
  function optionsOf(q) { return q.question_options || q.questionOptions || []; }
  function renderQuestions() { $('question-list').innerHTML=questions.length ? questions.map((q,i)=>`<article class="panel"><span class="badge">Question ${i+1} · ${esc(q.type)} · ${esc(q.marks)} marks</span><p class="question-stem">${esc(q.stem)}</p><div class="question-actions"><button data-question-edit="${esc(q.id)}" ${current?.is_active?'disabled':''}>Edit</button><button data-question-delete="${esc(q.id)}" ${current?.is_active?'disabled':''}>Delete</button></div></article>`).join('') : '<div class="notice">No questions yet. Add your first question after saving the paper.</div>'; state(); }
  function addOption(text='',correct=false,original={}) { const row=document.createElement('div'); row.className='option-row'; row.optionType=original.option_type || 'text'; row.codeLanguage=original.code_language || null; row.innerHTML=`<input type="checkbox" aria-label="Correct answer" ${correct?'checked':''}><input class="option-text" aria-label="Answer choice" value="${esc(text)}"><button type="button" data-remove-option>Remove</button>`; $('options').appendChild(row); }
  function questionType() { const type=value(qform,'type'); $('option-fields').hidden=!['mcq','multi_select','true_false'].includes(type); $('short-field').hidden=type!=='short_answer'; $('numerical-fields').hidden=type!=='numerical'; qform.elements.numerical_answer.required=type==='numerical'; if(type==='true_false' && !$('options').children.length) {addOption('True',true);addOption('False');} }
  function openQuestion(id) { if(current?.is_active){toast('Take this paper offline before editing questions.');return;} if(questionDirty && !confirm('Discard unsaved question changes?')) return; questionId=id || null; qform.reset(); $('options').innerHTML=''; const q=questions.find(row=>String(row.id)===String(id)); if(q) { for(const key of ['type','stem','marks','difficulty','explanation','numerical_answer','numerical_tolerance']) qform.elements.namedItem(key).value=q[key] ?? ''; qform.elements.acceptable_answers.value=(q.short_answer_acceptables || []).map(a=>a.acceptable_text).join('\n'); optionsOf(q).forEach(o=>addOption(o.option_text,o.is_correct,o)); } else {addOption();addOption();} questionType(); qform.hidden=false; $('question-title').textContent=q?'Edit question':'Add question'; qform.querySelector('.form-status').textContent=''; questionDirty=false; state(); qform.scrollIntoView({behavior:'smooth',block:'nearest'}); }
  function renderPreview() { if(!current) {$('paper-preview').innerHTML='<div class="notice">Save a paper first to preview it.</div>';return;} const course=courses.find(c=>String(c.id)===String(current.course_id)); $('paper-preview').innerHTML=`<article class="panel"><span class="badge">Manager preview · answer keys visible</span><h2>${esc(current.title)}</h2><p>${esc(course?.name)} · ${esc(current.section)}</p><p class="question-stem">${esc(current.description || '')}</p><p>${esc(money(current.price_paise))} · ${current.access_days?esc(current.access_days)+' days access':'No expiry'} · ${current.time_limit_minutes?esc(current.time_limit_minutes)+' minutes':'No time limit'}</p></article>${dirty || questionDirty?'<p class="notice">Save your changes before publishing. This preview shows saved content.</p>':''}${questions.map((q,i)=>`<article class="panel preview-question"><h3>Question ${i+1} · ${esc(q.marks)} marks</h3><p class="question-stem">${esc(q.stem)}</p>${q.stem_code?'<pre class="question-stem">'+esc(q.stem_code)+'</pre>':''}<ul>${optionsOf(q).map(o=>`<li>${esc(o.option_text)}${o.is_correct?' ✓ Correct':''}</li>`).join('')}</ul>${q.type==='numerical'?'<p>Answer: '+esc(q.numerical_answer)+' ± '+esc(q.numerical_tolerance)+'</p>':''}${q.type==='short_answer'?'<p>Accepted: '+esc((q.short_answer_acceptables||[]).map(a=>a.acceptable_text).join(', '))+'</p>':''}<p class="hint question-stem">${esc(q.explanation || '')}</p></article>`).join('')}`; state(); }
  /* ------------------------------ sales ------------------------------ */
  const rupees = value => money(value).replace(/\.00$/, '');
  const when = value => value ? new Date(value).toLocaleString('en-IN', {day:'numeric', month:'short', year:'numeric', hour:'numeric', minute:'2-digit'}) : '—';
  const STATES = {paid:['Paid','paid'], unpaid:['Not paid','unpaid'], paid_later:['Paid with a later order','later']};
  let orderStatus = '', searchTimer;
  function metric(label, figure, note, tone) { return `<div class="panel metric${tone ? ' '+tone : ''}"><span>${esc(label)}</span><strong>${esc(figure)}</strong><small>${esc(note)}</small></div>`; }
  async function loadSummary() {
    try {
      const data = await api('/manager/sales/summary'), t = data.totals || {};
      $('sales-metrics').innerHTML =
        metric('Total sales', rupees(t.revenue_paise), `${t.paid_orders || 0} paid ${t.paid_orders === 1 ? 'order' : 'orders'}`) +
        metric('Students who bought', t.buyers || 0, `Average sale ${rupees(t.average_paise)}`) +
        metric('Today', rupees(t.revenue_today_paise), `7 days ${rupees(t.revenue_7d_paise)} · 30 days ${rupees(t.revenue_30d_paise)}`) +
        metric('Checkout opened, not paid', t.unpaid_orders || 0, t.unpaid_orders ? `${t.unpaid_students} ${t.unpaid_students === 1 ? 'student' : 'students'} · ${rupees(t.unpaid_value_paise)} unpaid` : 'No unfinished checkouts', t.unpaid_orders ? 'warn' : '') +
        metric('Checkouts that paid', t.conversion_percent == null ? '—' : t.conversion_percent + '%', t.conversion_percent == null ? 'No checkouts yet' : 'Of all checkouts opened');
      const days = data.days || [], top = Math.max(1, ...days.map(d => d.revenue_paise));
      $('sales-days').innerHTML = days.some(d => d.orders) ? days.map(d => { const date = new Date(d.date + 'T00:00:00'); return `<div class="day" title="${esc(date.toLocaleDateString('en-IN', {day:'numeric', month:'short'}))}: ${esc(rupees(d.revenue_paise))} from ${esc(d.orders)} ${d.orders === 1 ? 'order' : 'orders'}"><b>${d.orders ? esc(rupees(d.revenue_paise)) : ''}</b><i style="height:${Math.round(d.revenue_paise / top * 100)}%"></i><span>${esc(date.toLocaleDateString('en-IN', {day:'numeric', month:'short'}))}</span></div>`; }).join('') : '<p class="hint">No sales in the last 14 days.</p>';
      const rows = data.papers || [];
      $('sales-papers').innerHTML = rows.length ? rows.map(p => `<tr><td><strong>${esc(p.title)}</strong><small>${esc(p.course_name || '')}${p.is_active ? '' : ' · Offline'}</small></td><td>${p.price_paise ? esc(rupees(p.price_paise)) : 'Free'}</td><td class="num">${esc(p.sold)}</td><td class="num">${esc(p.buyers)}</td><td class="num"><strong>${esc(rupees(p.revenue_paise))}</strong></td><td class="num">${p.unpaid ? '<span class="state unpaid">'+esc(p.unpaid)+'</span>' : '0'}</td></tr>`).join('') : `<tr><td colspan="6" class="empty-row">${t.paid_papers ? 'No paper has been bought yet.' : 'No paper has a price yet. Set one from Edit Quiz or the Papers tab.'}</td></tr>`;
      const picked = $('order-paper').value, options = new Map();
      rows.forEach(p => options.set(String(p.id), p.title)); papers.filter(p => Number(p.price_paise) > 0).forEach(p => options.set(String(p.id), p.title));
      $('order-paper').innerHTML = '<option value="">All papers</option>' + [...options].map(([id, title]) => `<option value="${esc(id)}">${esc(title)}</option>`).join(''); $('order-paper').value = options.has(picked) ? picked : '';
    } catch (error) { $('sales-metrics').innerHTML = '<div class="notice">' + esc(error.message) + '</div>'; }
  }
  function orderQuery(pageNumber, perPage) { const query = new URLSearchParams({page: pageNumber, per_page: perPage}); if (orderStatus) query.set('status', orderStatus); if ($('order-paper').value) query.set('quiz_id', $('order-paper').value); if ($('order-search').value.trim()) query.set('search', $('order-search').value.trim()); return '/manager/purchases?' + query; }
  async function loadPurchases() {
    $('purchase-list').innerHTML = '<tr><td colspan="7" class="empty-row">Loading orders…</td></tr>';
    try {
      const data = await api(orderQuery(page, 25)); page = data.current_page || page; lastPage = data.last_page || 1;
      const totals = data.totals || {};
      $('order-count').textContent = `${data.total ?? 0} ${data.total === 1 ? 'order' : 'orders'} · ${totals.paid_orders ?? 0} paid · ${rupees(totals.revenue_paise)} received`;
      $('purchase-list').innerHTML = data.data?.length ? data.data.map(o => { const [label, tone] = STATES[o.state] || STATES[o.status === 'paid' ? 'paid' : 'unpaid']; return `<tr><td><strong>${esc(o.user?.name || 'Deleted account')}</strong><small>${esc(o.user?.email || '')}</small></td><td>${esc(o.quiz?.title || 'Deleted paper')}<small>${esc(o.quiz?.course_name || '')}</small></td><td class="num">${esc(rupees(o.amount_paise))}</td><td><span class="state ${tone}">${esc(label)}</span></td><td>${esc(when(o.created_at))}</td><td>${esc(when(o.paid_at))}</td><td><small class="mono">${esc(o.razorpay_payment_id || o.razorpay_order_id || '—')}</small></td></tr>`; }).join('') : `<tr><td colspan="7" class="empty-row">${orderStatus || $('order-paper').value || $('order-search').value.trim() ? 'No orders match these filters.' : 'No student has opened a checkout yet.'}</td></tr>`;
      $('purchase-page').textContent = 'Page ' + page + ' of ' + lastPage; $('previous-purchases').disabled = page <= 1; $('next-purchases').disabled = page >= lastPage;
    } catch (error) { $('purchase-list').innerHTML = '<tr><td colspan="7" class="empty-row">' + esc(error.message) + '</td></tr>'; }
  }
  function loadSales() { loadSummary(); loadPurchases(); }
  function refilter() { page = 1; loadPurchases(); }
  async function exportOrders() {
    const rows = [['Student', 'Email', 'Paper', 'Course', 'Amount (INR)', 'Status', 'Checkout opened', 'Paid on', 'Razorpay order ID', 'Razorpay payment ID']];
    for (let n = 1, last = 1; n <= last && n <= 100; n++) { const data = await api(orderQuery(n, 100)); last = data.last_page || 1; (data.data || []).forEach(o => rows.push([o.user?.name, o.user?.email, o.quiz?.title, o.quiz?.course_name, (Number(o.amount_paise || 0) / 100).toFixed(2), (STATES[o.state] || [o.status])[0], o.created_at ? new Date(o.created_at).toISOString() : '', o.paid_at ? new Date(o.paid_at).toISOString() : '', o.razorpay_order_id, o.razorpay_payment_id])); }
    if (rows.length === 1) throw Error('There are no orders to download for these filters.');
    // A leading quote stops spreadsheet apps from running a cell as a formula.
    const cell = value => { let text = String(value ?? ''); if (/^[=+\-@\t\r]/.test(text)) text = "'" + text; return '"' + text.replace(/"/g, '""') + '"'; };
    const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob(['﻿' + rows.map(row => row.map(cell).join(',')).join('\r\n')], {type: 'text/csv'})); link.download = 'quiz-lab-orders-' + new Date().toISOString().slice(0, 10) + '.csv'; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(link.href), 1000);
  }
  document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{ document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b===button?'page':'false')); ['sales','papers','courses','deletion-requests'].forEach(t=>$(t+'-panel').hidden=t!==button.dataset.tab);if(button.dataset.tab==='sales')loadSales();if(button.dataset.tab==='deletion-requests')loadDeletionRequests(); });
  $('refresh-deletion-requests').onclick=loadDeletionRequests;
  $('deletion-request-filter').onchange=renderDeletionRequests;
  $('deletion-request-list').onchange=e=>{const select=e.target.closest('[data-deletion-status]');if(!select)return;const previous=deletionRequests.find(row=>String(row.id)===select.dataset.deletionStatus)?.status;select.disabled=true;api('/manager/account-deletion-requests/'+encodeURIComponent(select.dataset.deletionStatus),'PATCH',{status:select.value}).then(result=>{const index=deletionRequests.findIndex(row=>String(row.id)===select.dataset.deletionStatus);if(index>=0)deletionRequests[index]=result.request;renderDeletionRequests();toast('Request status updated.');}).catch(error=>{select.value=previous || 'pending';select.disabled=false;toast(error.message);});};
  document.querySelectorAll('[data-edit-tab]').forEach(b=>b.onclick=()=>editTab(b.dataset.editTab));
  function canClose(){return (!dirty && !questionDirty) || confirm('Close and discard unsaved changes?');}
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(canClose()){$(b.dataset.close).close();dirty=false;questionDirty=false;}});
  $('editor').addEventListener('cancel',e=>{if(!canClose())e.preventDefault();else{dirty=false;questionDirty=false;}});
  window.addEventListener('beforeunload',e=>{if(dirty || questionDirty){e.preventDefault();e.returnValue='';}});
  $('new-paper').onclick=()=>openEditor().catch(e=>toast(e.message)); $('paper-search').oninput=renderPapers;
  $('paper-list').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)busy(b,()=>openEditor(b.dataset.edit));};
  form.addEventListener('input',()=>{dirty=true;state();}); $('paper-course').onchange=()=>loadWeeks();$('paper-section').onchange=()=>loadWeeks();
  form.onsubmit=e=>{e.preventDefault();busy(form.querySelector('button'),async()=>{const payload={};for(const key of ['title','description','section'])payload[key]=value(form,key);for(const key of ['course_id','year','time_limit_minutes','access_days'])payload[key]=value(form,key)?Number(value(form,key)):null;payload.week_id=['practice','practice_graded'].includes(payload.section)?Number(value(form,'week_id')):null;payload.price_paise=Math.round(Number(value(form,'price'))*100);if(!Number.isSafeInteger(payload.price_paise))throw Error('Enter a valid price.'); current=await api('/manager/papers'+(current?'/'+current.id:''),current?'PUT':'POST',payload);dirty=false;form.querySelector('.form-status').textContent='Saved as an offline draft. Add questions, then preview and publish.';await refreshPapers();renderQuestions();state();toast('Paper saved.');},form.querySelector('.form-status'));};
  $('course-list').onclick=e=>{const b=e.target.closest('[data-course-toggle]');if(!b)return;const c=courses.find(row=>String(row.id)===b.dataset.courseToggle);if(!c)return;if(c.is_active && !confirm('Deactivate this course? Its papers will become unavailable to students until the course is activated again.'))return;busy(b,async()=>{await api('/manager/courses/'+c.id,'PUT',{is_active:!c.is_active});courses=await api('/manager/courses');renderCourses();await refreshPapers();toast(c.is_active?'Course deactivated.':'Course activated.');});};
  $('course-form').onsubmit=e=>{e.preventDefault();const f=e.target;busy(f.querySelector('button'),async()=>{await api('/manager/courses','POST',{name:value(f,'name'),level:value(f,'level'),description:value(f,'description'),weeks_count:Number(value(f,'weeks_count')),is_active:true});courses=await api('/manager/courses');renderCourses();f.reset();f.querySelector('.form-status').textContent='Course created. You can now select it when creating a paper.';},f.querySelector('.form-status'));};
  $('add-question').onclick=()=>openQuestion();$('add-option').onclick=()=>{addOption();questionDirty=true;state();};$('cancel-question').onclick=()=>{if(!questionDirty || confirm('Discard this unsaved question?')){qform.hidden=true;questionDirty=false;state();}};
  $('options').onclick=e=>{if(e.target.closest('[data-remove-option]')){e.target.closest('.option-row').remove();questionDirty=true;state();}};qform.addEventListener('input',()=>{questionDirty=true;state();});$('question-type').onchange=questionType;
  $('question-list').onclick=e=>{const edit=e.target.closest('[data-question-edit]'),del=e.target.closest('[data-question-delete]');if(edit)openQuestion(edit.dataset.questionEdit);if(del && confirm('Delete this question from the paper?'))busy(del,async()=>{await api('/manager/questions/'+del.dataset.questionDelete,'DELETE');questions=await api('/manager/papers/'+current.id+'/questions');current=await api('/manager/papers/'+current.id);renderQuestions();await refreshPapers();});};
  qform.onsubmit=e=>{e.preventDefault();busy(qform.querySelector('button.primary'),async()=>{if(!current)throw Error('Save the paper first.');if(current.is_active)throw Error('Take this paper offline before editing questions.');const payload={};for(const key of ['type','stem','explanation','difficulty'])payload[key]=value(qform,key);payload.marks=Number(value(qform,'marks'));payload.options=[...$('options').children].map((row,i)=>({option_type:row.optionType,code_language:row.codeLanguage,option_text:row.querySelector('.option-text').value.trim(),is_correct:row.querySelector('[type=checkbox]').checked,position:i}));if(['mcq','multi_select','true_false'].includes(payload.type)){if(payload.options.length<2 || payload.options.some(o=>!o.option_text))throw Error('Add at least two nonempty answer choices.');const correct=payload.options.filter(o=>o.is_correct).length;if(!correct || (payload.type!=='multi_select' && correct!==1))throw Error('Select '+(payload.type==='multi_select'?'at least one':'exactly one')+' correct answer.');if(payload.type==='true_false' && payload.options.length!==2)throw Error('True / false questions need two choices.');}payload.acceptable_answers=value(qform,'acceptable_answers').split('\n').map(s=>s.trim()).filter(Boolean);if(payload.type==='short_answer' && !payload.acceptable_answers.length)throw Error('Enter at least one accepted answer.');if(payload.type==='numerical'){payload.numerical_answer=Number(value(qform,'numerical_answer'));payload.numerical_tolerance=Number(value(qform,'numerical_tolerance'));}await api(questionId?'/manager/questions/'+questionId:'/manager/papers/'+current.id+'/questions',questionId?'PUT':'POST',payload);questions=await api('/manager/papers/'+current.id+'/questions');current=await api('/manager/papers/'+current.id);questionDirty=false;qform.hidden=true;renderQuestions();await refreshPapers();toast('Question saved. Review and publish when ready.');},qform.querySelector('.form-status'));};
  $('publish-paper').onclick=()=>busy($('publish-paper'),async()=>{if(dirty || questionDirty)throw Error('Save changes before publishing.');if(current.approval_status!=='approved')await api('/manager/papers/'+current.id+'/approve','PATCH',{});current=await api('/manager/papers/'+current.id+'/active','PATCH',{is_active:true});await refreshPapers();$('publish-status').textContent='Published. Students can now find this paper in the catalog.';renderQuestions();renderPreview();},$('publish-status')).finally(state);
  $('deactivate-paper').onclick=()=>busy($('deactivate-paper'),async()=>{current=await api('/manager/papers/'+current.id+'/active','PATCH',{is_active:false});await refreshPapers();$('publish-status').textContent='Paper is now offline.';renderQuestions();state();},$('publish-status')).finally(state);
  $('import-form').onsubmit=e=>{e.preventDefault();const f=e.target;busy(f.querySelector('button'),async()=>{if(!current || current.is_active)throw Error('Save an offline draft before importing questions.');if(questionDirty)throw Error('Save or cancel the question you are editing first.');let parsed;try{parsed=JSON.parse(value(f,'json'));}catch{throw Error('Enter valid JSON.');}const rows=Array.isArray(parsed)?parsed:parsed.questions;if(!Array.isArray(rows) || !rows.length)throw Error('Provide a nonempty questions array.');const result=await api('/manager/papers/'+current.id+'/questions/import-json','POST',{questions:rows,allow_partial:false});questions=await api('/manager/papers/'+current.id+'/questions');renderQuestions();await refreshPapers();f.reset();f.querySelector('.form-status').textContent=(result.imported_count || rows.length)+' questions imported.';},f.querySelector('.form-status'));};
  $('refresh-sales').onclick=loadSales;$('export-orders').onclick=()=>busy($('export-orders'),exportOrders);$('order-paper').onchange=refilter;$('order-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(refilter,300);};
  $('order-status').onclick=e=>{const b=e.target.closest('[data-status]');if(!b)return;orderStatus=b.dataset.status;$('order-status').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));refilter();};
  $('previous-purchases').onclick=()=>{if(page>1){page--;loadPurchases();}};$('next-purchases').onclick=()=>{if(page<lastPage){page++;loadPurchases();}};
  async function start(){try{if(!token())throw Error('Sign in with a manager account to manage paper sales.');const result=await api('/auth/me');const user=result.user || result;if(user.role!=='manager'){$('gate').textContent='Paper sales are for managers only. Taking you back…';location.replace(user.role==='admin'?'/admin':'/dashboard');return;}[courses,papers]=await Promise.all([api('/manager/courses'),api('/manager/papers')]);renderCourses();renderPapers();$('gate').hidden=true;$('workspace').hidden=false;loadSales();}catch(error){$('gate').innerHTML=esc(error.message)+' <a href="/login">Sign in</a> · <button id="retry-start">Retry</button>';$('retry-start').onclick=start;}}
  start();
})();
