(function () {
  'use strict';
  const $ = id => document.getElementById(id);
  const base = window.QLStorefront?.apiBase || 'https://labapi.genziitian.in/public/api';
  let courses = [], papers = [], current = null, questions = [], questionId = null, dirty = false, questionDirty = false, page = 1, lastPage = 1, toastTimer;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(value || 0)/100);
  const form = $('paper-form'), qform = $('question-form');
  const value = (f,key) => f.elements.namedItem(key).value;
  function token() { try { return localStorage.getItem('lab_token') || ''; } catch { return ''; } }
  function toast(text) { $('toast').textContent = text; $('toast').classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('toast').classList.remove('show'),5000); }
  async function api(path,method='GET',body) {
    const response = await fetch(base+path,{method,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:'Bearer '+token()},body:body === undefined ? undefined : JSON.stringify(body)});
    const data = await response.json().catch(() => ({}));
    if (response.status === 401) { try { localStorage.removeItem('lab_token'); localStorage.removeItem('lab_user'); } catch {} throw new Error('Your session expired. Sign in again, then reopen Manage sales.'); }
    if (!response.ok) { const errors = data.errors ? Object.values(data.errors).flat().join('\n') : ''; throw new Error(errors || data.message || data.error || 'Unable to complete this request. Please retry.'); }
    return data;
  }
  async function busy(button, action, status) { if (button.disabled) return; const original = button.textContent; button.disabled = true; button.textContent = 'Please wait…'; if (status) status.textContent = ''; try { await action(); } catch(error) { if(status) status.textContent = error.message; else toast(error.message); } finally {button.disabled=false;button.textContent=original;} }
  function state() { $('editor-state').textContent = current ? `${current.is_active ? 'Published' : 'Offline draft'} · ${questions.length} questions · ${money(current.price_paise)}${current.access_days ? ' · '+current.access_days+' days access' : ' · No expiry'}${dirty ? ' · Unsaved changes' : ''}` : 'New draft — save details before adding questions.'; $('add-question').disabled=!current || Boolean(current.is_active); $('question-lock').hidden=!current?.is_active; $('question-import').hidden=!current || Boolean(current.is_active); if (current?.is_active) qform.hidden=true; $('publish-paper').disabled=!current || dirty || questionDirty || !questions.length || Boolean(current.is_active); $('deactivate-paper').disabled=!current?.is_active; }
  function renderPapers() { const term=$('paper-search').value.trim().toLowerCase(); const rows=papers.filter(p => [p.title,p.course_name].join(' ').toLowerCase().includes(term)); $('paper-list').innerHTML=rows.length ? rows.map(p=>`<article class="card"><span class="badge ${p.is_active?'':'offline'}">${p.is_active?'Published':'Offline'}${p.approval_status!=='approved'?' · Review needed':''}</span>${p.course_active===false?'<span class="badge offline">Course inactive</span>':''}<h3>${esc(p.title)}</h3><p>${esc(p.course_name || p.course?.name)} · ${esc(p.section)}</p><p>${esc(p.questions_count || 0)} questions · ${esc(money(p.price_paise))}</p><button data-edit="${esc(p.id)}">Manage paper</button></article>`).join('') : '<div class="notice empty">No papers found. Create a paper to get started.</div>'; }
  async function refreshPapers() { papers=await api('/manager/papers'); renderPapers(); }
  function renderCourses() { $('course-list').innerHTML=courses.length ? courses.map(c=>`<article class="panel"><h3>${esc(c.name)}</h3><span class="badge">${esc(c.level)}</span><p class="hint">${esc(c.description || '')}</p><p>${c.is_active?'Active':'Inactive'}</p><button data-course-toggle="${esc(c.id)}">${c.is_active?'Deactivate course':'Activate course'}</button></article>`).join('') : '<div class="notice">Create your first course to organize its papers.</div>'; $('paper-course').innerHTML='<option value="">Choose a course</option>'+courses.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}${c.is_active?'':' (inactive)'}</option>`).join(''); }
  async function loadWeeks(selected) { const weekly=['practice','practice_graded'].includes(value(form,'section')); $('week-field').hidden=!weekly; $('paper-week').required=weekly; if(!weekly) return; $('paper-week').innerHTML='<option value="">Loading weeks…</option>'; if(!value(form,'course_id')) return; try { const rows=await api('/manager/courses/'+encodeURIComponent(value(form,'course_id'))+'/weeks'); $('paper-week').innerHTML='<option value="">Choose a week</option>'+rows.map(w=>`<option value="${esc(w.id)}">Week ${esc(w.week_number)}${w.title?' — '+esc(w.title):''}</option>`).join(''); if(selected) $('paper-week').value=selected; } catch(error){toast(error.message);} }
  function editTab(tab) { ['details','questions','preview'].forEach(name=>$(name+'-step').hidden=name!==tab); document.querySelectorAll('[data-edit-tab]').forEach(b=>b.classList.toggle('active',b.dataset.editTab===tab)); if(tab==='preview') renderPreview(); }
  async function openEditor(id) { if(dirty || questionDirty) { if(!confirm('Discard unsaved changes and open this paper?')) return; } form.reset(); qform.hidden=true; questionId=null; questions=[];dirty=false;questionDirty=false;current=null; form.querySelector('.form-status').textContent=''; $('publish-status').textContent=''; if(id) { current=await api('/manager/papers/'+id); questions=await api('/manager/papers/'+id+'/questions'); for(const key of ['title','description','course_id','section','year','time_limit_minutes','access_days']) form.elements.namedItem(key).value=current[key] ?? ''; form.elements.price.value=Number(current.price_paise || 0)/100; } $('editor-title').textContent=current?'Edit paper':'Create a paper'; await loadWeeks(current?.week_id); renderQuestions(); editTab('details'); state(); if(!$('editor').open) $('editor').showModal(); }
  function optionsOf(q) { return q.question_options || q.questionOptions || []; }
  function renderQuestions() { $('question-list').innerHTML=questions.length ? questions.map((q,i)=>`<article class="panel"><span class="badge">Question ${i+1} · ${esc(q.type)} · ${esc(q.marks)} marks</span><p class="question-stem">${esc(q.stem)}</p><div class="question-actions"><button data-question-edit="${esc(q.id)}" ${current?.is_active?'disabled':''}>Edit</button><button data-question-delete="${esc(q.id)}" ${current?.is_active?'disabled':''}>Delete</button></div></article>`).join('') : '<div class="notice">No questions yet. Add your first question after saving the paper.</div>'; state(); }
  function addOption(text='',correct=false,original={}) { const row=document.createElement('div'); row.className='option-row'; row.optionType=original.option_type || 'text'; row.codeLanguage=original.code_language || null; row.innerHTML=`<input type="checkbox" aria-label="Correct answer" ${correct?'checked':''}><input class="option-text" aria-label="Answer choice" value="${esc(text)}"><button type="button" data-remove-option>Remove</button>`; $('options').appendChild(row); }
  function questionType() { const type=value(qform,'type'); $('option-fields').hidden=!['mcq','multi_select','true_false'].includes(type); $('short-field').hidden=type!=='short_answer'; $('numerical-fields').hidden=type!=='numerical'; qform.elements.numerical_answer.required=type==='numerical'; if(type==='true_false' && !$('options').children.length) {addOption('True',true);addOption('False');} }
  function openQuestion(id) { if(current?.is_active){toast('Take this paper offline before editing questions.');return;} if(questionDirty && !confirm('Discard unsaved question changes?')) return; questionId=id || null; qform.reset(); $('options').innerHTML=''; const q=questions.find(row=>String(row.id)===String(id)); if(q) { for(const key of ['type','stem','marks','difficulty','explanation','numerical_answer','numerical_tolerance']) qform.elements.namedItem(key).value=q[key] ?? ''; qform.elements.acceptable_answers.value=(q.short_answer_acceptables || []).map(a=>a.acceptable_text).join('\n'); optionsOf(q).forEach(o=>addOption(o.option_text,o.is_correct,o)); } else {addOption();addOption();} questionType(); qform.hidden=false; $('question-title').textContent=q?'Edit question':'Add question'; qform.querySelector('.form-status').textContent=''; questionDirty=false; state(); qform.scrollIntoView({behavior:'smooth',block:'nearest'}); }
  function renderPreview() { if(!current) {$('paper-preview').innerHTML='<div class="notice">Save a paper first to preview it.</div>';return;} const course=courses.find(c=>String(c.id)===String(current.course_id)); $('paper-preview').innerHTML=`<article class="panel"><span class="badge">Manager preview · answer keys visible</span><h2>${esc(current.title)}</h2><p>${esc(course?.name)} · ${esc(current.section)}</p><p class="question-stem">${esc(current.description || '')}</p><p>${esc(money(current.price_paise))} · ${current.access_days?esc(current.access_days)+' days access':'No expiry'} · ${current.time_limit_minutes?esc(current.time_limit_minutes)+' minutes':'No time limit'}</p></article>${dirty || questionDirty?'<p class="notice">Save your changes before publishing. This preview shows saved content.</p>':''}${questions.map((q,i)=>`<article class="panel preview-question"><h3>Question ${i+1} · ${esc(q.marks)} marks</h3><p class="question-stem">${esc(q.stem)}</p>${q.stem_code?'<pre class="question-stem">'+esc(q.stem_code)+'</pre>':''}<ul>${optionsOf(q).map(o=>`<li>${esc(o.option_text)}${o.is_correct?' ✓ Correct':''}</li>`).join('')}</ul>${q.type==='numerical'?'<p>Answer: '+esc(q.numerical_answer)+' ± '+esc(q.numerical_tolerance)+'</p>':''}${q.type==='short_answer'?'<p>Accepted: '+esc((q.short_answer_acceptables||[]).map(a=>a.acceptable_text).join(', '))+'</p>':''}<p class="hint question-stem">${esc(q.explanation || '')}</p></article>`).join('')}`; state(); }
  async function loadPurchases() { $('purchase-list').innerHTML='<div class="notice">Loading purchases…</div>'; try {const data=await api('/manager/purchases?page='+page);page=data.current_page || page;lastPage=data.last_page || 1;const totals=data.totals || {}; $('purchase-totals').innerHTML=`<div class="panel">Orders<strong>${esc(totals.orders ?? 0)}</strong></div><div class="panel">Paid orders<strong>${esc(totals.paid_orders ?? 0)}</strong></div><div class="panel">Paid revenue<strong>${esc(money(totals.revenue_paise))}</strong></div>`; $('purchase-list').innerHTML=data.data?.length?data.data.map(o=>`<article class="purchase"><div><strong>${esc(o.quiz?.title || 'Paper')}</strong><p>${esc(o.user?.name)} · ${esc(o.user?.email)}</p><small>${esc(o.razorpay_order_id || 'Order '+o.id)} · ${esc(new Date(o.created_at).toLocaleString())}</small></div><div><span class="badge">${esc(o.status)}</span><p>${esc(money(o.amount_paise))}</p></div></article>`).join(''):'<div class="notice">No purchase records yet.</div>'; $('purchase-page').textContent='Page '+page+' of '+lastPage;$('previous-purchases').disabled=page<=1;$('next-purchases').disabled=page>=lastPage;}catch(error){$('purchase-list').innerHTML='<div class="notice">'+esc(error.message)+'</div>';}}
  document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{ document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b===button?'page':'false')); ['papers','courses','purchases'].forEach(t=>$(t+'-panel').hidden=t!==button.dataset.tab);if(button.dataset.tab==='purchases')loadPurchases(); });
  document.querySelectorAll('[data-edit-tab]').forEach(b=>b.onclick=()=>editTab(b.dataset.editTab));
  function canClose(){return (!dirty && !questionDirty) || confirm('Close and discard unsaved changes?');}
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(canClose()){$(b.dataset.close).close();dirty=false;questionDirty=false;}});
  $('editor').addEventListener('cancel',e=>{if(!canClose())e.preventDefault();else{dirty=false;questionDirty=false;}});
  window.addEventListener('beforeunload',e=>{if(dirty || questionDirty){e.preventDefault();e.returnValue='';}});
  $('new-paper').onclick=()=>openEditor().catch(e=>toast(e.message)); $('paper-search').oninput=renderPapers;
  $('paper-list').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)busy(b,()=>openEditor(b.dataset.edit));};
  form.addEventListener('input',()=>{dirty=true;state();}); $('paper-course').onchange=()=>loadWeeks();$('paper-section').onchange=()=>loadWeeks();
  form.onsubmit=e=>{e.preventDefault();busy(form.querySelector('button'),async()=>{const payload={};for(const key of ['title','description','section'])payload[key]=value(form,key);for(const key of ['course_id','year','time_limit_minutes','access_days'])payload[key]=value(form,key)?Number(value(form,key)):null;payload.week_id=['practice','practice_graded'].includes(payload.section)?Number(value(form,'week_id')):null;payload.price_paise=Math.round(Number(value(form,'price'))*100);if(!Number.isSafeInteger(payload.price_paise))throw Error('Enter a valid price.'); current=await api('/manager/papers'+(current?'/'+current.id:''),current?'PUT':'POST',payload);dirty=false;form.querySelector('.form-status').textContent='Saved as an offline draft. Add questions, then preview and publish.';await refreshPapers();renderQuestions();state();toast('Paper saved.');},form.querySelector('.form-status'));};
  $('course-list').onclick=e=>{const b=e.target.closest('[data-course-toggle]');if(!b)return;const c=courses.find(row=>String(row.id)===b.dataset.courseToggle);if(!c)return;if(c.is_active && !confirm('Deactivate this course? Its papers will become unavailable to students until the course is activated again.'))return;busy(b,async()=>{await api('/manager/courses/'+c.id,'PUT',{is_active:!c.is_active});courses=await api('/manager/courses');renderCourses();await refreshPapers();toast(c.is_active?'Course deactivated.':'Course activated.');});};
  $('course-form').onsubmit=e=>{e.preventDefault();const f=e.target;busy(f.querySelector('button'),async()=>{await api('/manager/courses','POST',{name:value(f,'name'),level:value(f,'level'),description:value(f,'description'),weeks_count:Number(value(f,'weeks_count')),is_active:true});courses=await api('/manager/courses');renderCourses();f.reset();f.querySelector('.form-status').textContent='Course created. You can now select it when creating a paper.';},f.querySelector('.form-status'));};
  $('add-question').onclick=()=>openQuestion();$('add-option').onclick=()=>{addOption();questionDirty=true;state();};$('cancel-question').onclick=()=>{if(!questionDirty || confirm('Discard this unsaved question?')){qform.hidden=true;questionDirty=false;state();}};
  $('options').onclick=e=>{if(e.target.closest('[data-remove-option]')){e.target.closest('.option-row').remove();questionDirty=true;state();}};qform.addEventListener('input',()=>{questionDirty=true;state();});$('question-type').onchange=questionType;
  $('question-list').onclick=e=>{const edit=e.target.closest('[data-question-edit]'),del=e.target.closest('[data-question-delete]');if(edit)openQuestion(edit.dataset.questionEdit);if(del && confirm('Delete this question from the paper?'))busy(del,async()=>{await api('/manager/questions/'+del.dataset.questionDelete,'DELETE');questions=await api('/manager/papers/'+current.id+'/questions');current=await api('/manager/papers/'+current.id);renderQuestions();await refreshPapers();});};
  qform.onsubmit=e=>{e.preventDefault();busy(qform.querySelector('button.primary'),async()=>{if(!current)throw Error('Save the paper first.');if(current.is_active)throw Error('Take this paper offline before editing questions.');const payload={};for(const key of ['type','stem','explanation','difficulty'])payload[key]=value(qform,key);payload.marks=Number(value(qform,'marks'));payload.options=[...$('options').children].map((row,i)=>({option_type:row.optionType,code_language:row.codeLanguage,option_text:row.querySelector('.option-text').value.trim(),is_correct:row.querySelector('[type=checkbox]').checked,position:i}));if(['mcq','multi_select','true_false'].includes(payload.type)){if(payload.options.length<2 || payload.options.some(o=>!o.option_text))throw Error('Add at least two nonempty answer choices.');const correct=payload.options.filter(o=>o.is_correct).length;if(!correct || (payload.type!=='multi_select' && correct!==1))throw Error('Select '+(payload.type==='multi_select'?'at least one':'exactly one')+' correct answer.');if(payload.type==='true_false' && payload.options.length!==2)throw Error('True / false questions need two choices.');}payload.acceptable_answers=value(qform,'acceptable_answers').split('\n').map(s=>s.trim()).filter(Boolean);if(payload.type==='short_answer' && !payload.acceptable_answers.length)throw Error('Enter at least one accepted answer.');if(payload.type==='numerical'){payload.numerical_answer=Number(value(qform,'numerical_answer'));payload.numerical_tolerance=Number(value(qform,'numerical_tolerance'));}await api(questionId?'/manager/questions/'+questionId:'/manager/papers/'+current.id+'/questions',questionId?'PUT':'POST',payload);questions=await api('/manager/papers/'+current.id+'/questions');current=await api('/manager/papers/'+current.id);questionDirty=false;qform.hidden=true;renderQuestions();await refreshPapers();toast('Question saved. Review and publish when ready.');},qform.querySelector('.form-status'));};
  $('publish-paper').onclick=()=>busy($('publish-paper'),async()=>{if(dirty || questionDirty)throw Error('Save changes before publishing.');if(current.approval_status!=='approved')await api('/manager/papers/'+current.id+'/approve','PATCH',{});current=await api('/manager/papers/'+current.id+'/active','PATCH',{is_active:true});await refreshPapers();$('publish-status').textContent='Published. Students can now find this paper in the catalog.';renderQuestions();renderPreview();},$('publish-status')).finally(state);
  $('deactivate-paper').onclick=()=>busy($('deactivate-paper'),async()=>{current=await api('/manager/papers/'+current.id+'/active','PATCH',{is_active:false});await refreshPapers();$('publish-status').textContent='Paper is now offline.';renderQuestions();state();},$('publish-status')).finally(state);
  $('import-form').onsubmit=e=>{e.preventDefault();const f=e.target;busy(f.querySelector('button'),async()=>{if(!current || current.is_active)throw Error('Save an offline draft before importing questions.');if(questionDirty)throw Error('Save or cancel the question you are editing first.');let parsed;try{parsed=JSON.parse(value(f,'json'));}catch{throw Error('Enter valid JSON.');}const rows=Array.isArray(parsed)?parsed:parsed.questions;if(!Array.isArray(rows) || !rows.length)throw Error('Provide a nonempty questions array.');const result=await api('/manager/papers/'+current.id+'/questions/import-json','POST',{questions:rows,allow_partial:false});questions=await api('/manager/papers/'+current.id+'/questions');renderQuestions();await refreshPapers();f.reset();f.querySelector('.form-status').textContent=(result.imported_count || rows.length)+' questions imported.';},f.querySelector('.form-status'));};
  $('refresh-purchases').onclick=loadPurchases;$('previous-purchases').onclick=()=>{if(page>1){page--;loadPurchases();}};$('next-purchases').onclick=()=>{if(page<lastPage){page++;loadPurchases();}};
  async function start(){try{if(!token())throw Error('Sign in with a manager account to manage paper sales.');const result=await api('/auth/me');const user=result.user || result;if(user.role!=='manager')throw Error('Only managers can access paper sales.');[courses,papers]=await Promise.all([api('/manager/courses'),api('/manager/papers')]);renderCourses();renderPapers();$('gate').hidden=true;$('workspace').hidden=false;}catch(error){$('gate').innerHTML=esc(error.message)+' <a href="/login">Sign in</a> · <button id="retry-start">Retry</button>';$('retry-start').onclick=start;}}
  start();
})();
